/**
 * Inbound email parsing: normalize Resend's `email.received` payload into the
 * fields the ingest path needs, and strip quoted reply history so the ingested
 * message is just what the visitor actually wrote.
 */
import { describe, it, expect } from 'vitest'
import {
  parseInboundEmail,
  parseRawEmail,
  extractReplyText,
  extractEmailAddress,
  parseMessageIdList,
  messageIdDomain,
  isAutoGeneratedEmail,
  decodeEncodedWords,
  normalizeSenderAddress,
  type ParsedInboundEmail,
} from '../conversation.email-inbound'

describe('parseInboundEmail', () => {
  it('normalizes an array `to`, reads `from`/`subject`/`text`, and the Message-ID header', () => {
    const parsed = parseInboundEmail({
      to: ['reply+conversation_abc@tenaevexeo.resend.app'],
      from: 'Jane Visitor <jane@example.com>',
      subject: 'Re: Your ticket',
      text: 'Thanks, that worked!',
      headers: [
        { name: 'Message-ID', value: '<msg-123@mail.example.com>' },
        { name: 'X-Other', value: 'ignored' },
      ],
    })
    expect(parsed.toAddresses).toEqual(['reply+conversation_abc@tenaevexeo.resend.app'])
    expect(parsed.from).toBe('Jane Visitor <jane@example.com>')
    expect(parsed.subject).toBe('Re: Your ticket')
    expect(parsed.text).toBe('Thanks, that worked!')
    expect(parsed.messageId).toBe('<msg-123@mail.example.com>')
  })

  it('accepts a string `to` and an object-shaped headers map (case-insensitive)', () => {
    const parsed = parseInboundEmail({
      to: 'reply+conversation_xyz@tenaevexeo.resend.app',
      from: 'bob@example.com',
      headers: { 'message-id': '<abc@x>' },
    })
    expect(parsed.toAddresses).toEqual(['reply+conversation_xyz@tenaevexeo.resend.app'])
    expect(parsed.messageId).toBe('<abc@x>')
  })

  it('falls back to the top-level email id when no Message-ID header is present', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      from: 'a@b.com',
      email_id: 'email_fallback_1',
    })
    expect(parsed.messageId).toBe('email_fallback_1')
  })

  it('captures the provider email id, and message_id outranks it for dedupe (#320)', () => {
    const withBoth = parseInboundEmail({
      to: ['x@y.com'],
      from: 'a@b.com',
      email_id: 'em_1',
      message_id: '<mid@provider>',
    })
    expect(withBoth.messageId).toBe('<mid@provider>')
    expect(withBoth.emailId).toBe('em_1')

    // A Message-ID header still wins for dedupe; emailId is unaffected by it.
    const withHeader = parseInboundEmail({
      to: ['x@y.com'],
      headers: [{ name: 'Message-ID', value: '<hdr@mail>' }],
      email_id: 'em_2',
    })
    expect(withHeader.messageId).toBe('<hdr@mail>')
    expect(withHeader.emailId).toBe('em_2')
  })

  it('returns empty/null fields for a junk payload rather than throwing', () => {
    const parsed = parseInboundEmail(null)
    expect(parsed.toAddresses).toEqual([])
    expect(parsed.from).toBeNull()
    expect(parsed.messageId).toBeNull()
    expect(parsed.emailId).toBeNull()
    expect(parsed.inReplyTo).toBeNull()
    expect(parsed.references).toEqual([])
    expect(parsed.html).toBeUndefined()
  })

  it('reads the html body field alongside text when a payload carries both', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      text: 'plain body',
      html: '<p>rich body</p>',
    })
    expect(parsed.text).toBe('plain body')
    expect(parsed.html).toBe('<p>rich body</p>')
  })

  it('reads the html body field when the payload has no plain-text field', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      html: '<p>only html</p>',
    })
    expect(parsed.text).toBeNull()
    expect(parsed.html).toBe('<p>only html</p>')
  })

  it('leaves html undefined when the payload has no html field', () => {
    const parsed = parseInboundEmail({ to: ['x@y.com'], text: 'plain only' })
    expect(parsed.html).toBeUndefined()
  })

  it('reads the threading + auto-mail headers', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      headers: [
        { name: 'In-Reply-To', value: '<a@d>' },
        { name: 'References', value: '<a@d> <b@d>' },
        { name: 'Auto-Submitted', value: 'auto-replied' },
        { name: 'Precedence', value: 'bulk' },
        { name: 'List-Id', value: 'news.example' },
      ],
    })
    expect(parsed.inReplyTo).toBe('a@d')
    expect(parsed.references).toEqual(['a@d', 'b@d'])
    expect(parsed.autoSubmitted).toBe('auto-replied')
    expect(parsed.precedence).toBe('bulk')
    expect(parsed.hasListHeaders).toBe(true)
  })

  it('captures cc recipients (array or string), empty when absent', () => {
    expect(parseInboundEmail({ to: 'x@y.com', cc: ['a@c.com', 'b@c.com'] }).ccAddresses).toEqual([
      'a@c.com',
      'b@c.com',
    ])
    expect(parseInboundEmail({ to: 'x@y.com', cc: 'solo@c.com' }).ccAddresses).toEqual([
      'solo@c.com',
    ])
    expect(parseInboundEmail({ to: 'x@y.com' }).ccAddresses).toEqual([])
  })

  it('leaves attachments undefined when the payload carries none', () => {
    expect(parseInboundEmail({ to: ['x@y.com'], text: 'hi' }).attachments).toBeUndefined()
    expect(parseInboundEmail({ to: ['x@y.com'], attachments: [] }).attachments).toBeUndefined()
  })

  it('maps provider attachment fields (base64 content, snake_case + camelCase)', () => {
    const png = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
    const pdf = Buffer.from('%PDF-1.4 mock')
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      text: 'see attached',
      attachments: [
        {
          filename: 'logo.png',
          content_type: 'image/png',
          content: png.toString('base64'),
          content_id: '<cid1@host>',
          content_disposition: 'inline',
        },
        { name: 'invoice.pdf', contentType: 'application/pdf', content: pdf.toString('base64') },
        { filename: 'empty.txt', content_type: 'text/plain', content: '' }, // dropped: no bytes
      ],
    })
    expect(parsed.attachments).toHaveLength(2)
    expect(parsed.attachments![0]).toMatchObject({
      filename: 'logo.png',
      contentType: 'image/png',
      contentId: 'cid1@host',
      disposition: 'inline',
    })
    expect(parsed.attachments![0].bytes.equals(png)).toBe(true)
    expect(parsed.attachments![1]).toMatchObject({
      filename: 'invoice.pdf',
      contentType: 'application/pdf',
      contentId: null,
      disposition: 'attachment',
    })
  })
})

describe('parseRawEmail', () => {
  it('parses headers and a plain-text body from a raw RFC822 message', () => {
    const raw = [
      'From: Jane Visitor <jane@example.com>',
      'To: reply+conversation_abc.sig@tenaevexeo.resend.app',
      'Subject: Re: ticket',
      'Message-ID: <m-1@example.com>',
      'In-Reply-To: <c.abc.n1@tenaevexeo.resend.app>',
      'References: <c.abc.n0@tenaevexeo.resend.app> <c.abc.n1@tenaevexeo.resend.app>',
      '',
      'This is my reply.',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.from).toBe('Jane Visitor <jane@example.com>')
    expect(parsed.toAddresses).toEqual(['reply+conversation_abc.sig@tenaevexeo.resend.app'])
    expect(parsed.subject).toBe('Re: ticket')
    expect(parsed.messageId).toBe('<m-1@example.com>')
    expect(parsed.inReplyTo).toBe('c.abc.n1@tenaevexeo.resend.app')
    expect(parsed.references).toEqual([
      'c.abc.n0@tenaevexeo.resend.app',
      'c.abc.n1@tenaevexeo.resend.app',
    ])
    expect(parsed.text).toBe('This is my reply.')
    expect(parsed.html).toBeUndefined()
  })

  it('unfolds a folded header (continuation line)', () => {
    const raw = ['Subject: a very long', ' folded subject', '', 'body'].join('\r\n')
    expect(parseRawEmail(raw).subject).toBe('a very long folded subject')
  })

  it('parses Cc recipients from the header', () => {
    const raw = [
      'To: support@acme.com',
      'Cc: alice@example.com, Bob <bob@example.com>',
      '',
      'body',
    ].join('\r\n')
    expect(parseRawEmail(raw).ccAddresses).toEqual(['alice@example.com', 'Bob <bob@example.com>'])
  })

  it('decodes a quoted-printable body', () => {
    const raw = [
      'Content-Type: text/plain',
      'Content-Transfer-Encoding: quoted-printable',
      '',
      'Caf=C3=A9 time =\n now',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('Café time  now')
    expect(parsed.html).toBeUndefined()
  })

  it('extracts both text/plain and text/html parts of a multipart/alternative message, one quoted-printable', () => {
    const raw = [
      'Content-Type: multipart/alternative; boundary="B"',
      '',
      '--B',
      'Content-Type: text/plain',
      '',
      'plain body here',
      '--B',
      'Content-Type: text/html',
      'Content-Transfer-Encoding: quoted-printable',
      '',
      '<p>Caf=C3=A9 html body</p>',
      '--B--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text?.trim()).toBe('plain body here')
    expect(parsed.html?.trim()).toBe('<p>Café html body</p>')
  })

  it('extracts the html part of an HTML-only (non-multipart) message', () => {
    const raw = [
      'Content-Type: text/html; charset=utf-8',
      '',
      '<p>Only an HTML body here.</p>',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('')
    expect(parsed.html).toBe('<p>Only an HTML body here.</p>')
  })

  it('extracts the html part of a multipart message with no text/plain part', () => {
    const raw = [
      'Content-Type: multipart/alternative; boundary="B"',
      '',
      '--B',
      'Content-Type: text/html',
      '',
      '<p>html-only alternative</p>',
      '--B--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('')
    expect(parsed.html?.trim()).toBe('<p>html-only alternative</p>')
  })

  it('leaves attachments undefined for a message that carries no MIME parts', () => {
    const raw = ['Content-Type: text/plain', '', 'just text'].join('\r\n')
    expect(parseRawEmail(raw).attachments).toBeUndefined()
  })

  it('does not overflow on a deeply nested multipart bomb (bounded recursion)', () => {
    // Each level nests a fresh multipart with a distinct boundary so the walk
    // truly recurses (a shared boundary would flatten via body.split). Without
    // a depth bound this overflows the stack; the poller would then retry the
    // message forever. 200 levels is well past the cap.
    const DEPTH = 200
    let raw = ['Content-Type: text/plain', '', 'deep body'].join('\r\n')
    for (let i = DEPTH; i > 0; i--) {
      const b = `B${i}`
      raw = [`Content-Type: multipart/mixed; boundary="${b}"`, '', `--${b}`, raw, `--${b}--`].join(
        '\r\n'
      )
    }
    // The assertion is simply that this returns rather than throwing RangeError.
    expect(() => parseRawEmail(raw)).not.toThrow()
  })
})

describe('parseRawEmail — MIME attachment parts (P4.4)', () => {
  const pngBytes = Buffer.from([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
  ])
  const pdfBytes = Buffer.from('%PDF-1.4\nmock invoice payload\n%%EOF')

  it('walks multipart/mixed(alternative(text,html-cid) + inline image + pdf) and collects both parts', () => {
    const raw = [
      'Content-Type: multipart/mixed; boundary="OUT"',
      '',
      'This is a multipart message in MIME format.',
      '--OUT',
      'Content-Type: multipart/alternative; boundary="ALT"',
      '',
      '--ALT',
      'Content-Type: text/plain',
      '',
      'Here is the logo.',
      '--ALT',
      'Content-Type: text/html',
      '',
      '<div dir="ltr">Here is the logo <img src="cid:logo123@host"></div>',
      '--ALT--',
      '--OUT',
      'Content-Type: image/png',
      'Content-Transfer-Encoding: base64',
      'Content-ID: <logo123@host>',
      'Content-Disposition: inline; filename="logo.png"',
      '',
      pngBytes.toString('base64'),
      '--OUT',
      'Content-Type: application/pdf; name="invoice.pdf"',
      'Content-Transfer-Encoding: base64',
      'Content-Disposition: attachment; filename="invoice.pdf"',
      '',
      pdfBytes.toString('base64'),
      '--OUT--',
    ].join('\r\n')

    const parsed = parseRawEmail(raw)
    expect(parsed.text?.trim()).toBe('Here is the logo.')
    expect(parsed.html).toContain('cid:logo123@host')
    expect(parsed.attachments).toHaveLength(2)

    const [img, pdf] = parsed.attachments!
    expect(img).toMatchObject({
      contentType: 'image/png',
      contentId: 'logo123@host',
      disposition: 'inline',
      filename: 'logo.png',
    })
    expect(img.bytes.equals(pngBytes)).toBe(true)

    expect(pdf).toMatchObject({
      contentType: 'application/pdf',
      contentId: null,
      disposition: 'attachment',
      filename: 'invoice.pdf',
    })
    expect(pdf.bytes.toString('utf8')).toContain('%PDF-1.4')
  })

  it('decodes a quoted-printable attachment part', () => {
    const raw = [
      'Content-Type: multipart/mixed; boundary="M"',
      '',
      '--M',
      'Content-Type: text/plain',
      '',
      'body',
      '--M',
      'Content-Type: text/calendar; name="event.ics"',
      'Content-Transfer-Encoding: quoted-printable',
      'Content-Disposition: attachment; filename="event.ics"',
      '',
      'SUMMARY:Caf=C3=A9',
      '--M--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.attachments).toHaveLength(1)
    expect(parsed.attachments![0].contentType).toBe('text/calendar')
    expect(parsed.attachments![0].bytes.toString('utf8').trim()).toBe('SUMMARY:Café')
  })
})

describe('decodeEncodedWords', () => {
  it('leaves plain ASCII untouched', () => {
    expect(decodeEncodedWords('Re: your question')).toBe('Re: your question')
    expect(decodeEncodedWords(null)).toBeNull()
    expect(decodeEncodedWords('')).toBe('')
  })

  it('decodes a Q-encoded word, treating _ as a space', () => {
    expect(decodeEncodedWords('=?UTF-8?Q?Caf=C3=A9_closed_early?=')).toBe('Café closed early')
  })

  it('decodes a B-encoded (base64) word', () => {
    const encoded = `=?UTF-8?B?${Buffer.from('Grüße aus Köln').toString('base64')}?=`
    expect(decodeEncodedWords(encoded)).toBe('Grüße aus Köln')
  })

  it('joins adjacent encoded-words without inserting the folding whitespace', () => {
    // A long subject is split across words; the space between them is folding,
    // not content, so it must not survive into the decoded string.
    expect(decodeEncodedWords('=?UTF-8?Q?Caf=C3=A9?= =?UTF-8?Q?_closed?=')).toBe('Café closed')
  })

  it('keeps literal whitespace between an encoded word and plain text', () => {
    expect(decodeEncodedWords('Re: =?UTF-8?Q?caf=C3=A9?= today')).toBe('Re: café today')
  })

  it('decodes a non-UTF-8 charset', () => {
    // ISO-8859-1 0xE9 is é — a single byte, unlike its UTF-8 encoding.
    expect(decodeEncodedWords('=?ISO-8859-1?Q?caf=E9?=')).toBe('café')
  })

  it('handles CJK and emoji subjects', () => {
    const jp = `=?UTF-8?B?${Buffer.from('請求について').toString('base64')}?=`
    expect(decodeEncodedWords(jp)).toBe('請求について')
    const emoji = `=?UTF-8?B?${Buffer.from('🚨 outage').toString('base64')}?=`
    expect(decodeEncodedWords(emoji)).toBe('🚨 outage')
  })

  it('keeps the original token when the charset is unknown', () => {
    // A mangled subject is better than a rejected message.
    expect(decodeEncodedWords('=?NOT-A-CHARSET?Q?abc?=')).toBe('=?NOT-A-CHARSET?Q?abc?=')
  })

  it('passes an invalid escape through rather than failing the whole word', () => {
    // `=ZZ` is not valid hex. Emitting the literal characters shows the reader
    // something closer to the intent than the raw `=?...?=` scaffolding would.
    expect(decodeEncodedWords('=?UTF-8?Q?ok_=ZZ?=')).toBe('ok =ZZ')
  })
})

describe('parseRawEmail — RFC 2047 headers', () => {
  it('decodes an encoded subject, sender display name, and attachment filename', () => {
    const raw = [
      'From: =?UTF-8?Q?Bj=C3=B6rn_Andr=C3=A9?= <bjorn@example.com>',
      'To: support@acme.test',
      '=?UTF-8?Q?Subject?=: ignored',
      'Subject: =?UTF-8?Q?Rechnung_f=C3=BCr_M=C3=A4rz?=',
      'Content-Type: multipart/mixed; boundary=b1',
      '',
      '--b1',
      'Content-Type: text/plain',
      '',
      'hallo',
      '--b1',
      'Content-Type: application/pdf; name="=?UTF-8?Q?Rechnung_M=C3=A4rz.pdf?="',
      'Content-Disposition: attachment; filename="=?UTF-8?Q?Rechnung_M=C3=A4rz.pdf?="',
      'Content-Transfer-Encoding: base64',
      '',
      Buffer.from('%PDF-1.4 fake').toString('base64'),
      '--b1--',
      '',
    ].join('\r\n')

    const parsed = parseRawEmail(raw)
    expect(parsed.subject).toBe('Rechnung für März')
    expect(parsed.from).toBe('Björn André <bjorn@example.com>')
    // The address still resolves once the display name is decoded.
    expect(normalizeSenderAddress(parsed.from)).toBe('bjorn@example.com')
    expect(parsed.attachments?.[0].filename).toBe('Rechnung März.pdf')
  })
})

describe('parseMessageIdList', () => {
  it('extracts all angle-bracketed ids, bare and trimmed', () => {
    expect(parseMessageIdList('<a@d>  <b@d>')).toEqual(['a@d', 'b@d'])
  })
  it('falls back to a bare, whitespace-free value', () => {
    expect(parseMessageIdList('bare@d')).toEqual(['bare@d'])
  })
  it('returns [] for null or a value with no usable id', () => {
    expect(parseMessageIdList(null)).toEqual([])
    expect(parseMessageIdList('no ids here')).toEqual([])
  })
})

describe('messageIdDomain', () => {
  it('reads the domain from an angle-bracketed or bare id', () => {
    expect(messageIdDomain('<x@Mail.Example.com>')).toBe('mail.example.com')
    expect(messageIdDomain('x@d')).toBe('d')
    expect(messageIdDomain(null)).toBeNull()
  })
})

describe('isAutoGeneratedEmail', () => {
  const base: ParsedInboundEmail = {
    toAddresses: [],
    ccAddresses: [],
    from: 'a@b.com',
    subject: null,
    text: 'hi',
    messageId: '<m@sender.example>',
    emailId: null,
    inReplyTo: null,
    references: [],
    autoSubmitted: null,
    autoResponseSuppress: null,
    precedence: null,
    hasListHeaders: false,
    authenticationResults: null,
  }

  it('passes an ordinary human reply', () => {
    expect(isAutoGeneratedEmail(base)).toBe(false)
    expect(isAutoGeneratedEmail({ ...base, autoSubmitted: 'no' })).toBe(false)
  })

  it('drops auto-submitted, suppressed, bulk/junk/list, and list mail', () => {
    expect(isAutoGeneratedEmail({ ...base, autoSubmitted: 'auto-replied' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, autoResponseSuppress: 'All' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'bulk' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'junk' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'list' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, hasListHeaders: true })).toBe(true)
  })

  it('drops our own mail looping back (Message-ID on one of our domains)', () => {
    const ownDomains = new Set(['sender.example'])
    expect(isAutoGeneratedEmail(base, ownDomains)).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, messageId: '<m@other.example>' }, ownDomains)).toBe(
      false
    )
  })
})

describe('extractReplyText', () => {
  it('drops a Gmail-style quoted history below "On … wrote:"', () => {
    const raw = [
      'This is my reply.',
      '',
      'On Mon, Jun 1, 2026 at 9:00 AM Support <reply+x@d> wrote:',
      '> previous agent message',
      '> more quoted text',
    ].join('\n')
    expect(extractReplyText(raw)).toBe('This is my reply.')
  })

  it('drops a leading-`>` quoted block with no separator line', () => {
    const raw = ['My answer is here.', '> quoted', '> quoted 2'].join('\n')
    expect(extractReplyText(raw)).toBe('My answer is here.')
  })

  it('strips a trailing signature after the "-- " delimiter', () => {
    const raw = ['Sounds good.', '', '-- ', 'Jane Visitor', 'Acme Inc'].join('\n')
    expect(extractReplyText(raw)).toBe('Sounds good.')
  })

  it('leaves a plain reply untouched (trimmed)', () => {
    expect(extractReplyText('  just a normal reply  ')).toBe('just a normal reply')
  })

  it('keeps a reply that begins with a "From:" prose line (not a forwarded header)', () => {
    expect(extractReplyText('From: my perspective this is broken\nplease help')).toBe(
      'From: my perspective this is broken\nplease help'
    )
  })

  it('keeps prose that merely contains a mid-body "From:" line', () => {
    const raw = 'I have two questions.\n\nFrom: the docs it says X\nCan you clarify?'
    expect(extractReplyText(raw)).toBe(raw)
  })

  it('falls back to the visitor text when a quote separator lands on the first line', () => {
    // Some clients put the attribution line first; cutting at it would drop the
    // whole message, so we recover the non-quoted text instead of returning "".
    expect(extractReplyText('On Mon, Jun 1, 2026 someone wrote:\nThanks, this is fixed now!')).toBe(
      'Thanks, this is fixed now!'
    )
  })

  it('still returns empty for a reply that is entirely quoted history', () => {
    expect(extractReplyText('On Mon wrote:\n> only quoted text\n> more quoted')).toBe('')
  })
})

describe('extractEmailAddress', () => {
  it('returns a bare address lowercased and trimmed', () => {
    expect(extractEmailAddress(' Jane@Example.COM ')).toBe('jane@example.com')
  })

  it('extracts the addr-spec from a name-addr From header', () => {
    expect(extractEmailAddress('Jane Visitor <Jane@Example.com>')).toBe('jane@example.com')
  })

  it('handles a quoted display name containing a comma', () => {
    expect(extractEmailAddress('"Doe, Jane" <jane@example.com>')).toBe('jane@example.com')
  })

  it('returns null for null, empty, or address-less input', () => {
    expect(extractEmailAddress(null)).toBeNull()
    expect(extractEmailAddress('')).toBeNull()
    expect(extractEmailAddress('not an address')).toBeNull()
  })

  it('returns null for malformed addr-specs', () => {
    expect(extractEmailAddress('Jane <@example.com>')).toBeNull()
    expect(extractEmailAddress('Jane <jane@>')).toBeNull()
    expect(extractEmailAddress('a@b@c')).toBeNull()
  })
})
