/**
 * Inbound email ingestion. Provider-neutral: `ingestParsedEmail` owns routing
 * and append, and every front door (the Resend webhook via `ingestInboundEmail`,
 * the IMAP poller) normalizes its input to a `ParsedInboundEmail` and feeds it
 * here. A message is routed into a conversation by its plus-address
 * (`reply+<id>@domain`) first, then — for replies whose client stripped the
 * plus-address — by matching its In-Reply-To/References against our stored
 * outbound Message-IDs. The visitor's stripped reply is appended through the
 * normal visitor-message path, so lifecycle (reopen), realtime publish and
 * offline notification all behave exactly as they do for a widget message.
 *
 * Auto-generated mail (autoresponders, bounces, list blasts, our own loops) is
 * dropped up front. The caller assumes an already-authenticated payload (the
 * webhook route is Svix-verified; IMAP owns the mailbox) and this never throws
 * on an unroutable one — it returns a status the caller maps to an ack + log.
 */
import { db, eq, sql, conversationMessages, conversations, principal, user } from '@/lib/server/db'
import type { ConversationAttachment } from '@/lib/server/db'
import type { ConversationId, PrincipalId, TicketId } from '@quackback/ids'
import type { Actor } from '@/lib/server/policy/types'
import { normalizePrincipalType } from '@/lib/server/functions/auth-helpers'
import { isBlocked } from '@/lib/server/domains/principals/blocking'
import { getReceivedEmail } from '@quackback/email'
import { realEmail } from '@/lib/shared/anonymous-email'
import { NotFoundError } from '@/lib/shared/errors'
import { logger } from '@/lib/server/logger'
import {
  parseInboundEmail,
  extractReplyText,
  extractEmailAddress,
  isAutoGeneratedEmail,
  isMailLoopEmail,
  normalizeSenderAddress,
  type ParsedInboundEmail,
} from './conversation.email-inbound'
import {
  conversationIdFromInboundAddress,
  ticketIdFromInboundAddress,
  ownEmailDomains,
} from './conversation.email-channel'
import { loadTicketOr404 } from '@/lib/server/domains/tickets/ticket.service'
import { appendInboundTicketReply } from '@/lib/server/domains/tickets/requester.service'
import { emailHtmlToContent } from '@/lib/server/content/email-html-to-content'
import {
  isS3Configured,
  uploadImageBuffer,
  uploadObject,
  generateStorageKey,
  MAX_FILE_SIZE,
} from '@/lib/server/storage/s3'
import { sniffImageMime, canonicalizeImageMime } from '@/lib/server/content/magic-bytes'
import { MAX_CONVERSATION_ATTACHMENTS } from '@/lib/shared/conversation/types'
import {
  resolveConversationByMessageIds,
  resolvePrincipalIdByEmail,
} from './conversation.email-store'
import {
  assertConversationSendRate,
  assertColdInboundRate,
  ConversationRateLimitError,
} from './conversation.ratelimit'
import { sendVisitorMessage } from './conversation.service'
import { resolveChannelAccountByRecipient } from '@/lib/server/domains/channel-accounts/channel-account.service'
import {
  resolveColdInboundSender,
  createEmailConversation,
  cleanupColdInboundLead,
} from './conversation.email-cold-inbound'
import { maybeAutoFileSpam } from './conversation.spam-filter'

export type IngestInboundResult =
  | { status: 'ingested'; conversationId: ConversationId }
  | { status: 'ingested_ticket'; ticketId: TicketId }
  | { status: 'duplicate' }
  | { status: 'no_conversation' }
  // A signed `tkt-` address that resolved but whose target/sender failed a check
  // (unknown/deleted/non-customer ticket, missing requester, sender ≠ requester),
  // or a `tkt-` address whose signature didn't verify. Always dropped — a ticket
  // address never creates a ticket/conversation and never reaches cold inbound.
  | { status: 'no_ticket' }
  | { status: 'empty' }
  | { status: 'from_mismatch' }
  | { status: 'rate_limited' }
  | { status: 'suppressed' }

const log = logger.child({ component: 'conversation-email-inbound' })

/** Own-storage prefixes for rehosted inbound media (mirror the composer upload
 *  routes: images share `chat-images`; non-image files get a sibling prefix). */
const INBOUND_IMAGE_PREFIX = 'chat-images'
const INBOUND_FILE_PREFIX = 'chat-files'
// Hard ceiling on how many parts a single inbound email may rehost to storage,
// covering inline images AND discrete attachments together. The discrete
// attachment tray is separately capped at MAX_CONVERSATION_ATTACHMENTS; this
// wider budget also bounds cid-referenced inline images (which don't consume an
// attachment slot) so a message stuffed with thousands of tiny inline images
// can't amplify into thousands of uploads.
const MAX_INBOUND_UPLOADS = 25

interface RehostedInboundMedia {
  /** The HTML body with `cid:` references rewritten to rehosted URLs, or the
   *  original html when nothing was rewritten. */
  html: string | undefined
  /** Discrete (non-inline) attachments to carry on the stored message. */
  attachments: ConversationAttachment[]
}

/** Does the HTML reference this Content-ID via a `cid:<id>` URL? */
function htmlReferencesCid(html: string, cid: string): boolean {
  return html.toLowerCase().includes(`cid:${cid.toLowerCase()}`)
}

/**
 * Rewrite every `cid:<id>` reference in the raw HTML to its rehosted https URL.
 * MUST run before `emailHtmlToContent` — its tiptap sanitize clears non-http(s)
 * `cid:` srcs, so an un-rewritten inline image would lose its source. Longest cid
 * first so a cid that's a prefix of another (`logo` vs `logo2`) can't corrupt it.
 */
function rewriteCidReferences(html: string, cidMap: Map<string, string>): string {
  let out = html
  for (const [cid, url] of [...cidMap].sort((a, b) => b[0].length - a[0].length)) {
    const escaped = cid.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    out = out.replace(new RegExp(`cid:${escaped}`, 'gi'), url)
  }
  return out
}

/**
 * Rehost inbound MIME attachment parts to workspace storage. Inline images whose
 * `cid:` is referenced in the HTML are rewritten into the body (they render as
 * inline images once `emailHtmlToContent` runs on the rewritten HTML); every
 * other part becomes a discrete `attachments[]` entry.
 *
 * Fail-soft by design: a part over the size cap, a declared image whose bytes
 * don't match (magic-byte check), an over-count attachment, or a failed upload is
 * dropped with a log line — a single bad part never fails the whole ingest.
 * Images upload via `uploadImageBuffer` (allow-list + `chat-images` prefix, the
 * same primitive the content rehoster uses); other files upload via the raw
 * `uploadObject` under `chat-files`, capped at `MAX_FILE_SIZE` (5 MB) — the same
 * limit the composer's image upload endpoint enforces (no discrete non-image
 * upload endpoint exists to mirror, so the shared 5 MB file cap applies).
 */
async function rehostInboundMedia(parsed: ParsedInboundEmail): Promise<RehostedInboundMedia> {
  const parts = parsed.attachments ?? []
  if (parts.length === 0) return { html: parsed.html, attachments: [] }
  if (!isS3Configured()) {
    log.warn({ count: parts.length }, 'inbound email media dropped: storage not configured')
    return { html: parsed.html, attachments: [] }
  }

  let html = parsed.html
  const cidMap = new Map<string, string>()
  const attachments: ConversationAttachment[] = []
  let uploads = 0

  for (const part of parts) {
    if (part.bytes.length === 0) continue
    // Total-upload ceiling: gates inline images too, so a message referencing
    // thousands of tiny cid: images can't amplify into thousands of S3 puts.
    if (uploads >= MAX_INBOUND_UPLOADS) {
      log.warn({ name: part.filename }, 'inbound email part dropped: over upload budget')
      continue
    }
    if (part.bytes.length > MAX_FILE_SIZE) {
      log.warn(
        { name: part.filename, size: part.bytes.length },
        'inbound email part dropped: over size cap'
      )
      continue
    }
    const declared = canonicalizeImageMime((part.contentType || '').toLowerCase())
    const isImage = declared.startsWith('image/')
    const referenced = !!part.contentId && !!html && htmlReferencesCid(html, part.contentId)

    if (isImage) {
      const sniffed = sniffImageMime(part.bytes)
      if (!sniffed || sniffed !== declared) {
        log.warn(
          { name: part.filename, declared, sniffed },
          'inbound email image dropped: bytes do not match declared type'
        )
        continue
      }
      // A discrete image consumes an attachment slot; a cid-referenced inline one
      // does not (it lands in the body), so only gate discrete images on the cap.
      if (!referenced && attachments.length >= MAX_CONVERSATION_ATTACHMENTS) {
        log.warn({ name: part.filename }, 'inbound email attachment dropped: over count cap')
        continue
      }
      let url: string
      try {
        ;({ url } = await uploadImageBuffer(part.bytes, sniffed, INBOUND_IMAGE_PREFIX))
      } catch (err) {
        log.warn({ err, name: part.filename }, 'inbound email image upload failed; skipped')
        continue
      }
      uploads++
      if (referenced && part.contentId) {
        cidMap.set(part.contentId, url)
      } else {
        attachments.push({
          url,
          name: part.filename || `image.${sniffed.split('/')[1] ?? 'img'}`,
          contentType: sniffed,
          size: part.bytes.length,
        })
      }
    } else {
      if (attachments.length >= MAX_CONVERSATION_ATTACHMENTS) {
        log.warn({ name: part.filename }, 'inbound email attachment dropped: over count cap')
        continue
      }
      const contentType = declared || 'application/octet-stream'
      let url: string
      try {
        const key = generateStorageKey(INBOUND_FILE_PREFIX, part.filename || 'attachment')
        url = await uploadObject(key, part.bytes, contentType)
      } catch (err) {
        log.warn({ err, name: part.filename }, 'inbound email attachment upload failed; skipped')
        continue
      }
      uploads++
      attachments.push({
        url,
        name: part.filename || 'attachment',
        contentType,
        size: part.bytes.length,
      })
    }
  }

  if (cidMap.size > 0 && html) html = rewriteCidReferences(html, cidMap)
  return { html, attachments }
}

/** Find the conversation id carried by any recipient plus-address. */
function conversationIdFromRecipients(toAddresses: string[]): string | null {
  for (const addr of toAddresses) {
    const id = conversationIdFromInboundAddress(addr)
    if (id) return id
  }
  return null
}

/** Find the verified ticket id carried by any recipient `reply+tkt-…` address. */
function ticketIdFromRecipients(toAddresses: string[]): TicketId | null {
  for (const addr of toAddresses) {
    const id = ticketIdFromInboundAddress(addr)
    if (id) return id as TicketId
  }
  return null
}

// The `reply+tkt-` marker claims a mail as ticket-destined regardless of whether
// its signature verifies. It only matches a ticket reply-to because the marker
// must sit immediately after `reply+`, and a conversation address puts its TypeID
// base32 suffix there (which never begins `tkt-`) — the `-` elsewhere in a
// base64url signature can't match this anchored prefix. Used to guarantee a
// forged/tampered `tkt-` address is DROPPED, not reinterpreted as a conversation
// reply or opened as cold inbound.
const TICKET_MARKER_RE = /reply\+tkt-/i

/** Does any recipient bear the `reply+tkt-` marker (verified or not)? */
function recipientsBearTicketMarker(toAddresses: string[]): boolean {
  return toAddresses.some((a) => TICKET_MARKER_RE.test(a))
}

/**
 * Route + append a parsed inbound email. Provider-neutral core shared by the
 * webhook and the IMAP poller.
 */
export async function ingestParsedEmail(parsed: ParsedInboundEmail): Promise<IngestInboundResult> {
  // Loop / auto-mail suppression before any work. A loop, a ticket-bound
  // auto-reply, or any auto mail carrying threading context stays a HARD drop
  // — never let an autoresponder or one of our own mails looping back fan out
  // a reply or append to a thread. A truly cold auto-generated mail (a bulk
  // blast to the support address with no thread context) is instead ingested
  // and filed to Spam by the signal layer, so it stays auditable in the Spam
  // view rather than vanishing. Runs BEFORE the ticket branch too, so an
  // auto-reply to a ticket notification never appends.
  const ownDomains = ownEmailDomains()
  if (isAutoGeneratedEmail(parsed, ownDomains)) {
    if (
      isMailLoopEmail(parsed, ownDomains) ||
      recipientsBearTicketMarker(parsed.toAddresses) ||
      conversationIdFromRecipients(parsed.toAddresses) !== null ||
      parsed.inReplyTo !== null ||
      parsed.references.length > 0
    ) {
      return { status: 'suppressed' }
    }
    return ingestColdInbound(parsed, { autoResponder: true })
  }

  // Ticket reply branch (D9): a signed `reply+tkt-…` recipient routes straight
  // into the ticket thread. Checked BEFORE conversation routing and cold inbound
  // so a `tkt-` address can never be reinterpreted as a conversation reply nor
  // opened as a fresh cold-inbound conversation — `ingestTicketReply` always
  // returns a terminal status. A `tkt-` mail whose signature failed to verify is
  // still ticket-destined: drop it here rather than let a forged address fall
  // through. Conversation addresses (no `tkt-` marker) skip this entirely.
  const ticketId = ticketIdFromRecipients(parsed.toAddresses)
  if (ticketId) return ingestTicketReply(parsed, ticketId)
  if (recipientsBearTicketMarker(parsed.toAddresses)) {
    log.warn(
      { reason: 'unverified_ticket_address' },
      'inbound ticket reply dropped: signature did not verify'
    )
    return { status: 'no_ticket' }
  }

  // Route: plus-address first, then the deterministic-Message-ID fallback for
  // replies whose client dropped the plus-address but kept the threading chain.
  let conversationId = conversationIdFromRecipients(parsed.toAddresses) as ConversationId | null
  if (!conversationId) {
    const candidates = [parsed.inReplyTo, ...parsed.references].filter(
      (id): id is string => id !== null
    )
    conversationId = await resolveConversationByMessageIds(candidates)
  }
  // Not a reply to any existing conversation: it may be a fresh email to one of
  // our inbound routes (§4.8 Layer 2 cold inbound), else there's nothing to do.
  if (!conversationId) return ingestColdInbound(parsed)

  // Idempotency first: a redelivered Message-ID short-circuits before any other
  // read (the common retry case). The partial unique index on
  // (metadata->>'emailMessageId') is the hard backstop; this makes a retry a
  // graceful no-op instead of a unique-violation.
  if (parsed.messageId) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${parsed.messageId}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  const conversation = await db.query.conversations.findFirst({
    where: eq(conversations.id, conversationId),
  })
  if (!conversation) return { status: 'no_conversation' }

  const plainText = extractReplyText(parsed.text ?? '')
  const hasAttachmentParts = (parsed.attachments?.length ?? 0) > 0
  if (!plainText && !parsed.html && !hasAttachmentParts) return { status: 'empty' }

  const visitorPrincipalId = conversation.visitorPrincipalId as PrincipalId
  const visitor = await db.query.principal.findFirst({
    where: eq(principal.id, visitorPrincipalId),
  })
  if (!visitor) return { status: 'no_conversation' }

  // The transport authenticates the delivery, not the SMTP sender: the reply+
  // address is visible to anyone on the email thread (CC, forward), so without
  // this check any third party could inject messages attributed to the visitor.
  // The From must match an address we know for this visitor — a linked account
  // email, the principal contact email, the captured pre-chat email, or a
  // recorded channel identity that resolves to this same visitor principal.
  // realEmail() keeps synthetic anonymous placeholders out of the set; an empty
  // set with no matching identity means nothing can match.
  const linkedUser = visitor.userId
    ? await db.query.user.findFirst({ where: eq(user.id, visitor.userId) })
    : null
  const knownAddresses = new Set(
    [linkedUser?.email, visitor.contactEmail, conversation.visitorEmail]
      .map((e) => realEmail(e))
      .filter((e): e is string => e !== null)
      .map((e) => e.toLowerCase())
  )
  const sender = extractEmailAddress(parsed.from)
  if (!sender) return { status: 'from_mismatch' }
  if (!knownAddresses.has(sender)) {
    const mappedPrincipalId = await resolvePrincipalIdByEmail(sender)
    if (mappedPrincipalId !== visitorPrincipalId) return { status: 'from_mismatch' }
  }

  // Blocked people cannot reply over email either; ack (200) so the provider
  // stops retrying, mirroring the widget send gate.
  if (await isBlocked(visitorPrincipalId)) return { status: 'suppressed' }

  // Same per-visitor throttle the widget send path enforces — the inbound email
  // channel must not be an unbounded back door for the offline-notification
  // fanout (a visitor mail-looping replies, or a client retrying with fresh
  // Message-IDs). Fails open on Redis errors. Ack (200) so the provider stops.
  try {
    await assertConversationSendRate(visitorPrincipalId)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) return { status: 'rate_limited' }
    throw err
  }

  const actor: Actor = {
    principalId: visitorPrincipalId,
    role: (visitor.role ?? null) as Actor['role'],
    principalType: normalizePrincipalType(visitor.type),
    segmentIds: new Set(),
  }

  // Rehost inbound media only now — after the sender is verified and the message
  // cleared the rate gate — so a forged / throttled mail never spends an upload.
  // Inline `cid:` images are rewritten into the HTML before conversion; other
  // files become discrete attachments. Convert the HTML body (rewritten) to a
  // rich doc + its plaintext mirror: text/plain keeps precedence for `content`
  // (the sender's own quote-trimmed words); the HTML supplies `contentJson` and,
  // for an HTML-only message, the `content` fallback.
  const media = await rehostInboundMedia(parsed)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    plainText || converted?.text || (media.attachments.length > 0 ? '' : '(no plain-text body)')
  const contentJson = converted?.contentJson ?? null

  await sendVisitorMessage(
    {
      conversationId,
      content,
      metadata: { source: 'email', emailMessageId: parsed.messageId ?? undefined },
      ...(media.attachments.length > 0 ? { attachments: media.attachments } : {}),
    },
    { principalId: visitorPrincipalId, displayName: visitor.displayName },
    actor,
    contentJson
  )

  return { status: 'ingested', conversationId }
}

/**
 * Cold inbound (§4.8 Layer 2): an email that isn't a reply. Only ingest it when
 * it's addressed to one of our inbound routes; otherwise it's not ours. The
 * DMARC-gated sender resolution decides drop / attach / create-lead, then a fresh
 * email conversation is opened. Dedup + empty-body guards mirror the reply path.
 */
async function ingestColdInbound(
  parsed: ParsedInboundEmail,
  opts: { autoResponder?: boolean } = {}
): Promise<IngestInboundResult> {
  const channelAccount = await resolveChannelAccountByRecipient([
    ...parsed.toAddresses,
    ...parsed.ccAddresses,
  ])
  if (!channelAccount || channelAccount.role !== 'inbound') return { status: 'no_conversation' }

  if (parsed.messageId) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${parsed.messageId}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  const plainText = extractReplyText(parsed.text ?? '')
  const hasAttachmentParts = (parsed.attachments?.length ?? 0) > 0
  if (!plainText && !parsed.html && !hasAttachmentParts) return { status: 'empty' }

  // An unparseable From is the one shape with no key to throttle on, and today
  // it mints a lead with a null contact email on a conversation nobody can ever
  // reply to. Drop it, reusing from_mismatch rather than growing the result union.
  const senderEmail = normalizeSenderAddress(parsed.from)
  if (!senderEmail) {
    log.warn({ reason: 'unparseable_from' }, 'cold inbound dropped')
    return { status: 'from_mismatch' }
  }

  // Throttle BEFORE resolution — resolution is what mints a principal, so a
  // gate placed after it has already let the row be created. Both this and the
  // block check below sit after the dedupe and empty-body guards so a provider
  // redelivery never burns a token.
  try {
    await assertColdInboundRate(senderEmail)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) return { status: 'rate_limited' }
    throw err
  }

  const resolution = await resolveColdInboundSender(parsed.from, parsed.authenticationResults)
  if (resolution.action === 'drop') return { status: 'suppressed' }

  // Blocked people cannot open a new thread by email either. Unconditional
  // rather than attach-only: a branch is more code than the one vacuous PK read
  // it would save on the create path. Placed before rehostInboundMedia so a
  // blocked sender never spends an upload — the ordering the reply and ticket
  // paths already use.
  if (await isBlocked(resolution.principalId)) {
    log.warn({ reason: 'sender_blocked' }, 'cold inbound dropped')
    return { status: 'suppressed' }
  }

  // Rehost media after the drop gates (never upload for a rejected sender). Same
  // precedence as the reply path: text/plain owns `content`; the rewritten HTML
  // supplies `contentJson` and the HTML-only `content` fallback.
  const media = await rehostInboundMedia(parsed)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    plainText || converted?.text || (media.attachments.length > 0 ? '' : '(no plain-text body)')

  let conversationId: ConversationId
  try {
    conversationId = await createEmailConversation({
      parsed,
      channelAccountId: channelAccount.id,
      principalId: resolution.principalId,
      unverified: resolution.unverified,
      content,
      contentJson: converted?.contentJson ?? null,
      attachments: media.attachments,
    })
  } catch (error) {
    if (resolution.action === 'create') {
      await cleanupColdInboundLead(resolution.principalId).catch(() => {})
    }
    throw error
  }

  // Spam filter, after the thread exists so a filing has something to land
  // on. Error-isolated inside (a classification failure leaves the thread in
  // triage, never breaks ingestion); the workspace trust list bypasses it.
  // The deterministic signals run first: auto-responder headers (this mail
  // arrived already flagged machine-generated) and a DMARC fail short of the
  // p=reject drop — either files to Spam without spending an AI completion.
  await maybeAutoFileSpam(conversationId, {
    senderEmail,
    subject: parsed.subject,
    content,
    signals: {
      autoResponder: opts.autoResponder === true,
      senderAuthFailed: resolution.verdict.dmarc === 'fail',
    },
  })
  return { status: 'ingested', conversationId }
}

/**
 * Reply-by-email (D9): append a verified inbound email onto the ticket named by a
 * signed `reply+tkt-…` recipient. Fails QUIET on every rejection — unknown /
 * deleted / non-`customer` ticket, missing requester, or a sender that isn't the
 * requester — with a structured `log.warn`, never creating a ticket or a
 * conversation and never bouncing. Only reached from `ingestParsedEmail` after the
 * RFC 3834 / loop guards and only for a signature-verified `tkt-` address, so the
 * transport is trusted; the remaining trust step is proving the SMTP sender is the
 * requester (the signed address alone is visible to anyone CC'd on a ticket mail).
 */
async function ingestTicketReply(
  parsed: ParsedInboundEmail,
  ticketId: TicketId
): Promise<IngestInboundResult> {
  // Idempotency: a redelivered Message-ID is a graceful no-op. The append stamps
  // `metadata.emailMessageId`, so this shares the same partial unique index the
  // conversation path relies on as the hard backstop.
  if (parsed.messageId) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${parsed.messageId}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  let ticket
  try {
    ticket = await loadTicketOr404(ticketId)
  } catch (err) {
    // A missing/deleted ticket is a quiet drop; a transient DB error must still
    // throw so the provider retries (mirrors the conversation path's behavior).
    if (err instanceof NotFoundError) {
      log.warn({ ticketId, reason: 'unknown_or_deleted_ticket' }, 'inbound ticket reply dropped')
      return { status: 'no_ticket' }
    }
    throw err
  }

  // Only `customer` tickets are a two-way requester thread; internal ticket types
  // have no requester to attribute an inbound reply to.
  if (ticket.type !== 'customer') {
    log.warn({ ticketId, reason: 'non_customer_ticket' }, 'inbound ticket reply dropped')
    return { status: 'no_ticket' }
  }
  const requesterPrincipalId = ticket.requesterPrincipalId as PrincipalId | null
  if (!requesterPrincipalId) {
    log.warn({ ticketId, reason: 'no_requester' }, 'inbound ticket reply dropped')
    return { status: 'no_ticket' }
  }

  // Sender verification: the From must match a known address for the requester.
  // Precedence mirrors `resolveReplyRecipient` — an identified requester's account
  // email, then the principal-level contact email. `realEmail()` keeps synthetic
  // anonymous placeholders out of the set; an empty set can never match.
  const requester = await db.query.principal.findFirst({
    where: eq(principal.id, requesterPrincipalId),
  })
  if (!requester) {
    log.warn({ ticketId, reason: 'requester_not_found' }, 'inbound ticket reply dropped')
    return { status: 'no_ticket' }
  }
  const linkedUser =
    requester.type !== 'anonymous' && requester.userId
      ? await db.query.user.findFirst({ where: eq(user.id, requester.userId) })
      : null
  const knownAddresses = new Set(
    [linkedUser?.email, requester.contactEmail]
      .map((e) => realEmail(e))
      .filter((e): e is string => e !== null)
      .map((e) => e.toLowerCase())
  )
  const sender = extractEmailAddress(parsed.from)
  if (!sender || !knownAddresses.has(sender)) {
    log.warn({ ticketId, reason: 'sender_not_requester' }, 'inbound ticket reply dropped')
    return { status: 'from_mismatch' }
  }

  // Blocked requesters cannot reply over email either; ack (drop, no bounce) so
  // the provider stops retrying, mirroring the conversation reply gate.
  if (await isBlocked(requesterPrincipalId)) {
    log.warn({ ticketId, reason: 'requester_blocked' }, 'inbound ticket reply dropped')
    return { status: 'suppressed' }
  }

  // Same per-principal throttle the conversation reply path enforces — the
  // inbound email channel must not be an unbounded back door for the ticket
  // watcher/agent fan-out (a mail loop or a client retrying with fresh
  // Message-IDs). Fails open on Redis errors.
  try {
    await assertConversationSendRate(requesterPrincipalId)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) return { status: 'rate_limited' }
    throw err
  }

  // Quoted-history stripping is identical to the conversation reply path.
  const plainText = extractReplyText(parsed.text ?? '')
  const hasAttachmentParts = (parsed.attachments?.length ?? 0) > 0
  if (!plainText && !parsed.html && !hasAttachmentParts) return { status: 'empty' }

  // Rehost media only now — after the sender is verified — so a forged mail never
  // spends an upload. Same content precedence as the conversation path: text/plain
  // (quote-trimmed) owns `content`; the rewritten HTML supplies `contentJson` and
  // the HTML-only `content` fallback.
  const media = await rehostInboundMedia(parsed)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    plainText || converted?.text || (media.attachments.length > 0 ? '' : '(no plain-text body)')

  await appendInboundTicketReply(
    ticketId,
    requesterPrincipalId,
    {
      content,
      contentJson: converted?.contentJson ?? null,
      ...(media.attachments.length > 0 ? { attachments: media.attachments } : {}),
      metadata: { source: 'email', emailMessageId: parsed.messageId ?? undefined },
    },
    normalizePrincipalType(requester.type)
  )

  return { status: 'ingested_ticket', ticketId }
}

/**
 * Webhook front door: normalize a provider `email.received` event's parsed
 * `data` and ingest it. Kept as the stable entry point the Resend webhook
 * handler calls.
 */
export async function ingestInboundEmail(event: unknown): Promise<IngestInboundResult> {
  const data =
    (event && typeof event === 'object' ? (event as { data?: unknown }).data : null) ?? null
  const parsed = parseInboundEmail(data)

  // Resend's `email.received` webhook is metadata-only — it carries no text/html
  // body. When the payload has no body but exposes the provider email id, fetch
  // the full message from the Received Emails API (#320) and normalize it onto
  // the parsed shape before the provider-neutral core runs. The IMAP front door
  // never hits this (it carries the full RFC822 body, and `emailId` is null).
  // `not_found`/no-API-key → null → falls through to the normal empty-body drop;
  // any other fetch error throws → the webhook route 500s → Resend redelivers
  // (idempotent via the Message-ID dedupe + the partial unique index).
  if (!parsed.text && !parsed.html && parsed.emailId) {
    const full = await getReceivedEmail(parsed.emailId)
    if (full?.text) parsed.text = full.text
    if (full?.html) parsed.html = full.html
  }

  return ingestParsedEmail(parsed)
}
